### ISSUE TITLE
[Bug report] cli cgz cannot start

### ISSUE THREAD

**Issue by ichaozai** [Zhengqbbb/cz-git#115]
### ✅ Checklist

- [X] I am using the **latest version**
- [X] I have searched [FAQ](https://cz-git.qbb.sh/faq/)

### 📄 System Info

```Shell
$ npx envinfo --system --binaries --npmPackages cz-git --npmPackages commitizen --npmPackages czg --npmGlobalPackages cz-git --npmGlobalPackages commitizen --npmGlobalPackages czg
npx: installed 1 in 2.254s

  System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz
    Memory: 13.59 GB / 15.51 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    npm: 6.14.4 - /usr/bin/npm
  npmGlobalPackages:
    commitizen: 4.3.0
    czg: 1.6.1
```

#### Concise Description

I use Windows WSL2.
After install cgz
```
$ sudo npm install -g czg
```
```
$ czg --help
(node:763) UnhandledPromiseRejectionWarning: Error: Not supported
    at Object.<anonymous> (/usr/local/lib/node_modules/czg/bin/index.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
(node:763) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:763) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Zhengqbbb** [comment]
Thanks for the feedback, it seems Node v10 compatibility issues,
If you can you can use `commitizen CLI` + `cz-git `first, or upgrade `Node` version >= 12

**Comment by Zhengqbbb** [comment]
The czg have been release a next version. you can have try `1.6.2-beta.2`

```sh
npm install -g czg@1.6.2-beta.2
```

**Comment by Zhengqbbb** [comment]
@ichaozai 

- Unfortunately, the czg CLI does not work on Node v10
- Because our TUI dependency `inquirer@8.2.4` in commitizen is already in use and does not support Node v10. 
- `czg` has been using this version of the dependency since it was released.

Of course, if you are using commitizen v4.3.0, it won't work either

<img width="1454" alt="image" src="https://user-images.githubusercontent.com/40693636/227446445-34545e47-b01b-41e6-9c71-a587311b865a.png">

But there is an alternative, `commitizen@4.2.6` + `cz-git@1.3.8`
```sh
npm install -g commitizen@4.2.6 cz-git@1.3.8
echo '{ "path": "cz-git" }' > .czrc
cz # or `git cz`
```

<img width="986" alt="CleanShot 2023-03-24 at 14 50 22@2x" src="https://user-images.githubusercontent.com/40693636/227446561-a298624e-1d5f-49fa-adbf-68d367f55ef5.png">


I will make a note in the documentation, thanks again for your feedback
