### ISSUE TITLE
[Feature Request] Allow to skip type

### ISSUE THREAD

**Issue by cletter7** [Zhengqbbb/cz-git#146]
### 💭 Describe the feature

In the monorepo I am working with we only need scope and not the type. We don't actually use the commit type for generating changelog, etc., but we still want to be able to see which package was impacted by some specific commit by its name. So currently we are using type as a scope and then use `formatMessageCB` to put the type in the place of scope. Something like:
```js
formatMessageCB: ({ type, subject }) => `(${type}): ${subject}`
```

But in this case we are not able to choose multiple packages as you can only select one type. Ideally I'd like to skip type and be able to choose multiple options from the scope.

Could you make type skippable?

### 💡 Proposed Solution

Add possibility to specify `type` in the `skipQuestions` option so that the type question is skipped. Example:
```js
skipQuestions: ['type']
```

**Comment by Zhengqbbb** [comment]
Actually it didn't configure's type support because I didn't add it because cz-git follows the standard [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) specification.

**But it can also work !!!** : skipQuestions: ['type']

Below is my understanding of the configuration implementation. If you have other needs, welcome leave message

```js
{
    skipQuestions: ['type', 'body', 'breaking', 'footerPrefix', 'footer'],
    enableMultipleScopes: true,
    formatMessageCB: ({ scope, subject }) => scope ? `(${scope}): ${subject}` : subject,
}
```

https://github.com/Zhengqbbb/cz-git/assets/40693636/b9d005bc-c357-4243-9cfc-468876f0d0fc

**Comment by cletter7** [comment]
It works indeed. Just [here](https://cz-git.qbb.sh/config/engineer#skipquestions) the type of `skipQuestions` doesn't say that you can skip the `type` so I didn't even try it. Maybe worth updating the docs.

Thank you, closing the issue.
