### ISSUE TITLE
[Feature Request] Support commitlint.config.mjs extension

### ISSUE THREAD

**Issue by zigang93** [Zhengqbbb/cz-git#177]
### 💭 Describe the feature

support esm module file. 
using `import` statement

**Comment by Zhengqbbb** [comment]
I apologize, but at the beginning of the project, I started experimenting with compatibility in this area, which proved infeasible due to upstream dependencies:

1. The CLI must be started using the Common JS method because the Terminal UI library inquirer@8.2.4 used by commitizen requires CJS, and commitizen is currently very inactive, so I don't think it will be updated.
2. If I use the CJS method to start and obtain ESM configuration, an error will occur.

https://github.com/commitizen/cz-cli/blob/28d96ef98d702dc48c7a19d44dce710ab80911ba/package.json#L84
https://github.com/SBoudrias/Inquirer.js/tree/inquirer%408.2.4

---

However, there is still a way to achieve this, which is to use [@esbuild-kit/cjs-loader](https://www.npmjs.com/package/@esbuild-kit/cjs-loader) to convert the CJS compatibility layer and provide it to the cz-git configuration.
https://github.com/element-plus/element-plus/blob/dev/commitlint.config.js
playground: https://github.com/Zhengqbbb/czgit-playground/tree/commitizen-esm

**Comment by Zhengqbbb** [comment]
BTW I'm curious why it's necessary to use `commitlint.config.mjs`. Emmm as far as I know, `commitlint.config.cjs` can also achieve the validation effect.

**Comment by zigang93** [comment]
btw, I able to make it work with `.js` only..
and make my monorepo root packages.json with `"type": module"`.. 

I had tried to change `.cjs` but it don't work..

I want to use `.mjs` because I don't want to use `"type": module"` in my packages.json.. it will force my source code to use esm only.. mjs is standalone config file.. I saw `@commitlint/cli` got support `mjs`..

**Comment by Zhengqbbb** [comment]
> make my monorepo root packages.json with `"type": module"`. I had tried to change `.cjs` but it don't work..

Oh that is something wrong. It should work. If you try to read `js` in your type:modules project, it will use the ESM paradigm to read it. However, if your file is `cjs`, it will forcibly use the CJS method to read the configuration.

**Comment by zigang93** [comment]
> > make my monorepo root packages.json with `"type": module"`. I had tried to change `.cjs` but it don't work..
> 
> Oh that is something wrong. It should work. If you try to read `js` in your type:modules project, it will use the ESM paradigm to read it. However, if your file is `cjs`, it will forcibly use the CJS method to read the configuration.
> 
> Have a reproduction repo 👀 ?

I try reproduce for u :) will update to u within 2 days

**Comment by Zhengqbbb** [comment]
Hi there, I plan to add support for loading ESM configuration files in v1.11.0 next weekend.
I have released a next pre-release version 🌟(v1.11.0-beta.1)🌟 for testing.
Welcome to try it out! 👀 Let me know if there are still any issues. 🎉

Docs preview link: https://deploy-preview-197--cz-git.netlify.app/config/
Example: https://github.com/Zhengqbbb/czgit-playground/tree/commitizen-esm

**Comment by zigang93** [comment]
> Hi there, I plan to add support for loading ESM configuration files in v1.11.0 next weekend. I have released a next pre-release version 🌟(v1.11.0-beta.1)🌟 for testing. Welcome to try it out! 👀 Let me know if there are still any issues. 🎉
> 
> Docs preview link: https://deploy-preview-197--cz-git.netlify.app/config/ Example: https://github.com/Zhengqbbb/czgit-playground/tree/commitizen-esm

it is working. :)

**Comment by Zhengqbbb** [comment]
Hi there 👋
The latest version 🌟(v1.11.0)🌟 released and supported ESM configure loading.
Docs Link: https://cz-git.qbb.sh/config/
💪 Please have a try. 👀 Let me know if there are still any issues. 🎉
