### ISSUE TITLE
[Feature Request]Is it possible to provide a function or command that only produces a message?

### ISSUE THREAD

**Issue by shlroland** [Zhengqbbb/cz-git#194]
### 💭 Describe the feature

In certain scenarios, I need to generate clean messages that can be copied for use. For example, when making some temporary commits on GitHub Gitea or using some Git GUI clients.

**Comment by Zhengqbbb** [comment]
Could you describe it in more detail?
Specifically, the requirements and the desired effect, preferably with screenshots.

**Comment by shlroland** [comment]
In simple terms, it may just mean removing the detection of the current git staging files and the final real submission steps, that is, using only the prompt to generate the final message.

<img width="672" alt="image" src="https://github.com/user-attachments/assets/af9d06d4-e1bf-44ff-912c-a3c1a231d661">

**Comment by Zhengqbbb** [comment]
> Is it possible to provide a function or command that only produces a message?

I understand, you want to get the results just like `--dry-run`, right?

I also wanted to achieve this because I need to commit to 6 repositories at once and a unified submission.
However, I wasn't successful because my Terminal UI library [inquirer](https://github.com/Zhengqbbb/cz-git/blob/e7b50ccc75221cf031f0a4a1a063aea7320f60d0/pnpm-workspace.yaml#L14) I used didn't strictly follow stderr and instead occupied my stdout, which resulted in the final output being added to the TUI element. So I'm sorry about that.

**Comment by Zhengqbbb** [comment]
If I have new ideas or methods, I will reopen or notify
